# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Junteng Liu
name: Junteng Liu
description: First-year PhD candidate at HKUST NLP Group, working on Natural Language Processing and Machine Learning.
url: https://paintskyheat.github.io
baseurl: /LJT-Homepage/
#
# this will use the lovely "plainwhite" theme:
remote_theme: "pages-themes/minima@v2.5.1"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Author info
author:
  name: Junteng Liu
  avatar: prof_pic.jpg
  bio: "First-year PhD candidate researching Natural Language Processing and Machine Learning at HKUST NLP Group"
  location: Hong Kong
  email: jliugi@connect.ust.hk
  github_username: Vicent0205
  google_scholar: https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate
  twitter_username: junteng88716710

# Social links
social:
  type: person
  name: Junteng Liu
  url: https://paintskyheat.github.io/LJT-Homepage
  sameAs:
    - https://github.com/Vicent0205
    - https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate
    - https://twitter.com/junteng88716710

# Other configurations
github: [metadata]
repository: paintskyheat/LJT-Homepage

# Publications collection
collections:
  - publications

# Site navigation
header_pages:
  - _pages/about.md
  - _pages/publications.html

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - Dockerfile
  - docker-compose.yaml
  - talkmap.ipynb
  - talkmap.py
  - talkmap_out.ipynb
